services:
  php81:
    container_name: php81
    build: ../php81/
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "${CRON_PATH}:/etc/cron.d/schedule-cron"
      - "../php81/php_ini/php.ini:/usr/local/etc/php/php.ini"
      - "../php81/php_ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini"
    command: >
      bash -c "chmod 0777 /etc/cron.d/schedule-cron
      && crontab /etc/cron.d/schedule-cron
      && service cron restart
      && php-fpm"
    ports:
      - 3000:3000
    depends_on:
      - mysql8
    networks:
      - asia-yo

  mysql8:
    container_name: mysql8
    image: mysql:8.0.28-oracle
    platform: linux/arm64/v8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - asia-yo-mysql8:/var/lib/mysql
    networks:
      - asia-yo
  
  nginx:
    container_name: nginx
    build: ../nginx/
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "${NGINX_LOG_PATH}:/var/log/nginx"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/conf.d/sites:/etc/nginx/conf.d/sites
    networks:
      - asia-yo

networks:
  asia-yo:


volumes:
  asia-yo-mysql8: